version: '3'
services:
  gitea:
    image: gitea/gitea:1.16.7
    # build:
    #   context: .
    #   dockerfile: Dockerfile-gitea
    container_name: gitea
    environment:
      - GITEA__security__INSTALL_LOCK=true
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__mailer__ENABLED=false
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__log__LEVEL=Trace
      - GITEA__log__FLAGS=date,time,level
      - GITEA__server__ROOT_URL=http://localhost:8889
      - GITEA__server__HTTP_PORT=8889
    restart: always
#    volumes:
#      - gitea-volume:/data
    #   - :/etc/timezone:ro
    #   - :/etc/localtime:ro
    ports:
      - "8889:8889"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea


  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
      args:
        CACHEBUST: 2
    depends_on:
      - gitea
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- jenkins-workspace-volume:/var/jenkins_home/
    environment:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-""}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-""}
        AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-""}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-""}
    env_file:
      - "../git.env"

  jenkins-graviton:
    build:
      context: .
      dockerfile: Dockerfile-node
    hostname: docker-node
    depends_on:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-graviton-workspace-volume:/workspace
    environment:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-""}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-""}
        AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-""}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-""}
        WORKER_NAME: ec2-worker-u20-graviton
    env_file:
      - "../git.env"

  jenkins-amd64:
    build:
      context: .
      dockerfile: Dockerfile-node
    hostname: docker-node
    depends_on:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-amd64-workspace-volume:/workspace
    environment:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-""}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-""}
        AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-""}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-""}
        WORKER_NAME: ec2-worker-u18-medium
    env_file:
      - "../git.env"

  verdaccio:
    build:
      context: .
      dockerfile: Dockerfile-verdaccio
    ports:
      - '4873:4873'

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports:
      - '8081:8081'

  aws:
    image: localstack/localstack:0.12.17
    environment:
      - SERVICES=s3,ssm,sqs,secretsmanager
    ports:
      - '4566:4566'

  kubeconfig-server:
    build:
      context: .
      dockerfile: Dockerfile-kubeconfig
    ports:
      - "8082:80"



volumes:
  jenkins-workspace-volume:
  jenkins-graviton-workspace-volume:
  jenkins-amd64-workspace-volume:
  gitea-volume:
