version: '3'
services:
  gitlab:
    build:
      context: .
      dockerfile: Dockerfile-gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['initial_root_password'] = "password"
        gitlab_rails['store_initial_root_password'] = true
    env_file:
      - "../git.env"
    ports:
      - '8000:80'
      - '2224:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-log:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
      args:
        CACHEBUST: 2
    depends_on:
      - gitlab
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-workspace-volume:/var/jenkins_home/
    environment:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-""}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-""}
        AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-""}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-""}
    env_file:
      - "../git.env"

  jenkins-node:
    build:
      context: .
      dockerfile: Dockerfile-node
    hostname: docker-node
    depends_on:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-node-workspace-volume:/workspace
    environment:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-""}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-""}
        AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-""}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-""}

  verdaccio:
    build:
      context: .
      dockerfile: Dockerfile-verdaccio
    ports:
      - '4873:4873'

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports:
      - '8081:8081'

  aws:
    image: localstack/localstack:0.12.17
    environment:
      - SERVICES=s3,ssm,sqs
    ports:
      - '4566:4566'

  kubeconfig-server:
    build:
      context: .
      dockerfile: Dockerfile-kubeconfig
    ports:
      - "8082:80"



volumes:
  jenkins-workspace-volume:
  jenkins-node-workspace-volume:
  gitlab-config:
  gitlab-log:
  gitlab-data: