#!/bin/bash -e
docker compose kill jenkins && docker compose rm -f jenkins
# docker compose kill jenkins-amd64 && docker compose rm -f jenkins-amd64
docker compose kill jenkins-amd64-u22-1 && docker compose rm -f jenkins-amd64-u22-1
docker compose kill jenkins-amd64-u22-2 && docker compose rm -f jenkins-amd64-u22-2
docker compose kill jenkins-graviton-u22 && docker compose rm -f jenkins-graviton-u22
docker compose kill custom-node && docker compose rm -f custom-node
docker compose kill gitea && docker compose rm -f gitea
./up
